### ISSUE TITLE
Every after 2-3 days No activity, No earning..

### ISSUE THREAD

**Issue by yogeshnichal** [helium/miner#1244] opened 2021-11-22 06:49 UTC
I have 7 miners and If I'm correct every miner world average earning 5-6 HNT/month
Every day my earnings going down..

I have an outdoor antenna on rooftop, LMR400 cable, not relayed, in city, fast internet connection
I've multiple times checked my wires and antenna. What is the possibility, please explain the massive drop off in activity? I am well aware that earnings fluctuates...But in the last 30 days dropping.

![Shot 0159](https://user-images.githubusercontent.com/56922233/142810180-172d5607-860f-4961-997c-cd03ea0f4ac7.png)
![Shot 0160](https://user-images.githubusercontent.com/56922233/142810185-15844359-40b2-4ebb-a0be-94a0772f342e.png)
![Shot 0161](https://user-images.githubusercontent.com/56922233/142810188-7bf3f76c-b8e1-4498-906c-e8f34a6a3f07.png)
![Shot 0162](https://user-images.githubusercontent.com/56922233/142810189-1d9ab401-793d-4d3a-8381-f20811bd6fac.png)
![Shot 0163](https://user-images.githubusercontent.com/56922233/142810191-93b7fa59-7283-48ca-ac3f-669b5638b4d4.png)

**Comment by shawaj** [comment] 2021-11-22 14:43
The earnings will drop as more hotspots are added to the network.

Also there have been a couple of block halts the last week see status.helium.com

**Comment by yogeshnichal** [comment] 2021-11-22 18:31
See this no sent beacons

![Shot 0165](https://user-images.githubusercontent.com/56922233/142915926-dccc9368-8ca5-47ba-af0e-0794305102a1.png)
![Shot 0166](https://user-images.githubusercontent.com/56922233/142915934-5d4e079c-001d-4ea0-b309-e410f5004c6b.png)

**Comment by Chinik12** [comment] 2021-11-23 14:50
i'm SENSECAP and from 17days no election for send beacon, why? it's random, but in 17 days a lot of block and election.
[Activity](https://explorer.helium.com/hotspots/1121u7LTwLwLKDwCHzkVmj4uv8CxDxcPLwxUJzSsT1PkDk26Gjrv/activity)
![image](https://user-images.githubusercontent.com/93588105/143044676-65018a8d-a7c0-462e-97fe-93df09e437cc.png)
![image](https://user-images.githubusercontent.com/93588105/143044708-c8152bf2-77b0-418d-bc9e-3f7bab81a272.png)

**Comment by JeroenIoT** [comment] 2021-11-27 07:54
Flatliners for my hotspots. From mining 1+ HNT/day to flatliners (started approx november 11).
Hotspot no changes made. All checked

<img width="274" alt="image" src="https://user-images.githubusercontent.com/14053463/143673179-35efb6d2-eb94-43a6-aaee-ed1590fd95bc.png">

<img width="503" alt="image" src="https://user-images.githubusercontent.com/14053463/143673238-8a935cbd-f575-4a22-a0a0-cfeee5b1e1d7.png">

**Comment by yogeshnichal** [comment] 2021-11-27 16:45
Why this problem happening? No sent beacons :( :( No earning..
![Shot 0026](https://user-images.githubusercontent.com/56922233/143689738-7c1f6907-09a1-4f91-acfd-712a286e10ea.png)
![Shot 0028](https://user-images.githubusercontent.com/56922233/143689742-e161bfbc-5e42-4016-915f-fe5903abe8e4.png)

**Comment by Pappa-Bear** [comment] 2021-11-28 05:07
Are these miners using an LTE connection for internet? There seems to be a problem with 4G connections since one of the updates a few weeks ago - I have 2 miners doing exactly the same thing for the last 19 days. Yesterday I went to one of my host sites that is using LTE and switch the LTE off and moved onto the hosts wifi...instantly started witnessing again like it used to. Still not sent a beacon but at least it's witnessing and earning again.
![image](https://user-images.githubusercontent.com/95157626/143730370-72464b7f-0e9c-43fc-982a-09939f99f92f.png)
See the other thread about this issue on here

**Comment by amirhaleem** [comment] 2021-11-29 21:15
probably a dupe of #1205, closing for now

**Closed by amirhaleem** 2021-11-29 21:15 UTC
