### ISSUE TITLE
Activity drop by 96%

### ISSUE THREAD

**Issue by Davekted** [helium/miner#1259] opened 2021-11-26 21:36 UTC
Hey all,

i have a good spot.
Clear view 33 mtrs height.
https://explorer.helium.com/hotspots/11QGUWZjMpHM1rrRfrm8xo88gTJkDPgxY2b497FFBuM5xWLoMmh
from activity every 15 minutes to 6 a day....
sometimes 14 hours no activity. Wth is going on.
![image](https://user-images.githubusercontent.com/95023956/143656613-a5a32da5-aab7-436d-9095-da2c485dd05e.png)
![image](https://user-images.githubusercontent.com/95023956/143419135-fbef07aa-0e90-4ad9-bcb5-8af3201c771e.png)
![image](https://user-images.githubusercontent.com/95023956/143419220-c3db9c66-73ef-4b4a-bf49-930d405e3770.png)

**
-
-
-

- And this was before the problems.
- 
- Around November 1st.

**
![image](https://user-images.githubusercontent.com/95023956/143419513-4d8f4c70-9e39-4f56-88b1-19a8f67cc1b2.png)

_Originally posted by @Davekted in https://github.com/helium/miner/issues/1088#issuecomment-979045365_

**Comment by houssam62** [comment] 2021-11-27 17:02
I have the same issue, our setups are almost the same. Also sensecap. But in addition to your issue, my hotspot hasn't beaconed in over 11 days.
https://explorer.helium.com/hotspots/117m5RWURbofi8UedAtHSFtQ7kd198m9EzqFjP3cGQJyBmeq1Md

**Comment by DominicAusHollandia** [comment] 2021-11-28 16:06
I have the same issue. In addition to that I also send no beacons. Sensecap 36m height

**Comment by amirhaleem** [comment] 2021-11-29 22:10
probably a dupe of #1205, closing for now

**Closed by amirhaleem** 2021-11-29 22:10 UTC

**Comment by Davekted** [comment] 2021-12-03 07:17
@amirhaleem still no difference.

![image](https://user-images.githubusercontent.com/95023956/144561040-b142d7f6-22c5-4ff6-8f3a-36e470f5084e.png)
![image](https://user-images.githubusercontent.com/95023956/144561072-be9862dc-b9a9-4e41-b318-731543ff3dc7.png)
![image](https://user-images.githubusercontent.com/95023956/144561230-ca2f8e51-51fb-474f-ab68-00a4941d51cb.png)
