### ISSUE TITLE
POC11 issue on AS923 countries

### ISSUE THREAD

**Issue by Trinitrophenol81** [helium/miner#1105] opened 2021-09-30 02:31 UTC
With the new POC11 , AS923 countries would have an issue  .  Lora alliance set up the default EIRP of AS923 to 16dbm.
But different Asia countries has set the max EIRP to around 26-27dbm. 
Singapore regulations max EIRP is 27dBm. Indonesia EIRP is 26dBm, for example.
If helium is adopting 16dbm for AS923 , that could be an big issue for us. Our coverage will severely limited.
I would suggest a country specific EIRP limiting rather than a blanket wide setting of 16dbm .

**Comment by Heliumblur** [comment] 2021-09-30 02:51
Yes, this will totally destroy the Helium hotspots in the Asian region.

**Comment by ubiru** [comment] 2021-09-30 02:54
i wanna add something here. I am wondering if Helium is using the Lora Alliance Guideline for every freq region. If yes, then AS923 will be set at 16dBm EIRP in POC11. But AS923 is used by many countries in East & South East Asia countries and they have different regulation for the EIRP.
if the EIRP set up by Helium for AS923 is at 16dBm, then it would severely limit the tx power of the helium hotspots using in AS923 region countries. So if using high gain antenna, it will create big blankspot area surrounding the hotspot, but coverage would be shorter too. Meanwhile, if using low gain antenna, with the reduction of EIRP set by Helium automatically to the hotspots, then the tx power would be greatly reduce and maybe can't penetrate buildings (concrete walls) in Asian countries.
need some clarification on this matter and revision if necessary from the Helium Core Dev Team.

**Comment by Vagabond** [comment] 2021-09-30 16:46
We can certainly make changes there if you can provide links to the documentation of the EIRP limits in those regions. Thanks for reporting this.

cc @vihu

**Comment by shannon786tamiz** [comment] 2021-09-30 22:12
Hi, I intend to purchase a number of Helium (HNT) Hotspot miners for use in Bangladesh.
The issue I'm having is regarding the correct frequency units to mine HNT in Bangladesh.

According to the Helium's Github list, AS923_1 is the frequency for Bangladesh to mine HNT.

https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv
https://docs.helium.com/lorawan-on-helium/frequency-plans/

However, according to the LoRa site information it indicates the EU433 and another list states EU868 may be compatible so this is where I'm stuck on deciding.

All of the current suppliers of the Helium Hotspot miners have been contacted but only a few responded with unclear information.
Linxdot have confirmed their 915MHz version also extends to AS923_1 which is listed per the Helium Github list for Bangladesh.

https://store.linxdot.com/products/linxdot-indoor-hotspot

I would be very grateful if you can please confirm which frequency is correct for Bangladesh regarding Helium mining?
Or the LoRa  listed frequencies are perhaps the standard but Helium has chosen AS923_1?

Thank you very much.

**Comment by ubiru** [comment] 2021-10-01 00:40
#> We can certainly make changes there if you can provide links to the documentation of the EIRP limits in those regions. Thanks for reporting this.
> 
> cc @vihu

Hi, This is the link for the document that governed the LPWAN devices in Indonesia.
https://jdih.kominfo.go.id/produk_hukum/unduh/id/676/t/peraturan+menteri+komunikasi+dan+informatika+nomor+1+tahun+2019+tanggal+24+april+2019

![676_signed pdf - PDFlite 01_10_2021 07_16_51](https://user-images.githubusercontent.com/90969626/135548647-c1645d32-75ee-45e3-b0ff-640dc9d132c7.png)

You can find the above doc page for the EIRP info for LPWA non cellular 920-923 MHz regulated on the last page (page 22) of the document. For Gateway it's set at 400mW (or 26dBm). Let me know if you can't download the pdf doc from that site.

**Comment by Trinitrophenol81** [comment] 2021-10-01 00:49
> We can certainly make changes there if you can provide links to the documentation of the EIRP limits in those regions. Thanks for reporting this.
> 
> cc @vihu

Please see link (page 36) for the IMDA Singapore regulations for EIRP
(https://www.imda.gov.sg/-/media/Imda/Files/Regulation-Licensing-and-Consultations/Frameworks-and-Policies/Spectrum-Management-and-Coordination/SpectrumMgmtHB.pdf?la=en)
I included the screenshot from the document for easy reference
![IMDA](https://user-images.githubusercontent.com/89213271/135549259-87e2f860-22c5-4a37-9962-da1af08133bb.jpg)

**Comment by Trinitrophenol81** [comment] 2021-10-02 02:43
For Malaysia , EIRP limit is also at 500mW

![Malaysia EIRP](https://user-images.githubusercontent.com/89213271/135701342-64fa19b4-4707-4e7c-b80a-f48fb680a179.jpg)

Source https://www.skmm.gov.my/skmmgovmy/media/General/pdf/Technical_Report_IoT.pdf

**Comment by 4kt3680** [comment] 2021-10-04 08:31
For Thailand, maximum EIRP is 4W EIRP (with installation license) and 500mW EIRP (non installation license). Refer from [NBTC-1033](http://www.ratchakitcha.soc.go.th/DATA/PDF/2560/E/289/51.PDF) and [NBTC-rachkitcha](https://www.nbtc.go.th/Business/commu/radio/licensing/%E0%B8%81%E0%B8%8E%E0%B8%AB%E0%B8%A1%E0%B8%B2%E0%B8%A2%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%80%E0%B8%81%E0%B8%B5%E0%B9%88%E0%B8%A2%E0%B8%A7%E0%B8%82%E0%B9%89%E0%B8%AD%E0%B8%87/%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%81%E0%B8%B2%E0%B8%A8-%E0%B8%81%E0%B8%AA%E0%B8%97%E0%B8%8A-%E0%B9%80%E0%B8%A3%E0%B8%B7%E0%B9%88%E0%B8%AD%E0%B8%87-%E0%B9%80%E0%B8%84%E0%B8%A3%E0%B8%B7%E0%B9%88%E0%B8%AD%E0%B8%87%E0%B8%A7%E0%B8%B4%E0%B8%97%E0%B8%A2%E0%B8%B8%E0%B8%84%E0%B8%A1%E0%B8%99%E0%B8%B2%E0%B8%84%E0%B8%A1%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%B5%E0%B8%A7%E0%B8%B4%E0%B8%97%E0%B8%A2.aspx)

![image](https://user-images.githubusercontent.com/91874515/135818513-254873a2-4fd3-418c-a1ae-06fde5e5cb68.png)

**Comment by hollejacklin** [comment] 2021-10-12 02:06
In Taiwan, the EIRP limit is 0.5W
![image](https://user-images.githubusercontent.com/91720232/136878953-839046ef-8801-4809-8860-9db3dc30f53d.png)

Source: [NCC in Tanwan](https://www.ncc.gov.tw/english/files/20081/LP0002%20Low-power%20Radio-frequency%20Devices%20Technical%20Regulations.pdf)  section 5.8.1.2 page 34

**Comment by sokolmk** [comment] 2021-10-14 18:10
@Vagabond I would like to report that in North Macedonia the maximum allowed e.r.p at 868 MHz is 500mW, or 27DbM
On the website of the Agency for electronic communication, the Plan for the allocation and use of radio frequencies in the Republic of Northern Macedonia is posted. 
[Link to the agency post](https://aek.mk/%D0%BF%D0%BB%D0%B0%D0%BD-%D0%B7%D0%B0-%D0%BD%D0%B0%D0%BC%D0%B5%D0%BD%D0%B0-%D0%BD%D0%B0-%D1%80%D0%B0%D0%B4%D0%B8%D0%BE%D1%84%D1%80%D0%B5%D0%BA%D0%B2%D0%B5%D0%BD%D1%86%D0%B8%D1%81%D0%BA%D0%B8-%D0%BE/)
[Link to the actual plan](https://aek.mk/wp-content/uploads/2021/03/20210319-Plan-za-dodeluvanje-i-koristenje-na-radiofrekvencii.pdf)
The plan is posted on the Official Gazette of the Republic of North Macedonia, no. 50 dated 3.3.2021
On page 64 you can see that the frequency range of 863-868Mhz is governed by the North Macedonian standard МКС EN 302 208.  
![868](https://user-images.githubusercontent.com/92541291/137372334-6351be9f-adc2-451c-8e08-d2c1133708ec.png)

On the website of the Standardization Institute of the Republic of North Macedonia you can see that the МКС EN 302 208 standard is identical to EN 302 208-1 V2.1.1:2015)
[Link to the website's post](https://isrsm.gov.mk/en/project/show/isrsm:proj:52372)
When you open the [EN 302 208-1 V2.1.1:2015](https://www.etsi.org/deliver/etsi_en/302200_302299/30220801/02.01.01_60/en_30220801v020101p.pdf) standard on page 24 you will find the transmission limits in the lower band 865 MHz to 868 MHz to be 500mW
![eirp](https://user-images.githubusercontent.com/92541291/137372138-bd5b949e-c5e0-4359-a49b-037619d21e9a.png)

**Comment by Jamiulhasib** [comment] 2021-11-17 16:34
> Hi, I intend to purchase a number of Helium (HNT) Hotspot miners for use in Bangladesh. The issue I'm having is regarding the correct frequency units to mine HNT in Bangladesh.
> 
> According to the Helium's Github list, AS923_1 is the frequency for Bangladesh to mine HNT.
> 
> https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv https://docs.helium.com/lorawan-on-helium/frequency-plans/
> 
> However, according to the LoRa site information it indicates the EU433 and another list states EU868 may be compatible so this is where I'm stuck on deciding.
> 
> All of the current suppliers of the Helium Hotspot miners have been contacted but only a few responded with unclear information. Linxdot have confirmed their 915MHz version also extends to AS923_1 which is listed per the Helium Github list for Bangladesh.
> 
> https://store.linxdot.com/products/linxdot-indoor-hotspot
> 
> I would be very grateful if you can please confirm which frequency is correct for Bangladesh regarding Helium mining? Or the LoRa listed frequencies are perhaps the standard but Helium has chosen AS923_1?
> 
> Thank you very much.

hi, I am jamiul from Bangladesh, I am also interested to mining Helium but I am really new about this product, I need some help from some experienced person like you. If you have no problem then please guide me about Helium mining and also frequency and other issues.
I am waiting for your responce
Take care
Jamiul

**Comment by resyncX** [comment] 2021-12-14 14:50
> We can certainly make changes there if you can provide links to the documentation of the EIRP limits in those regions. Thanks for reporting this.
> 
> cc @vihu

Hi @Vagabond @vihu 

Now that PoCv11 is live with the blanket 16dbm defined for the entire AS923, we can see the impact quite drastically for AS923 countries.
In the past 20hrs, we are seeing more than ~50% drop in witnessing others and beacons being witnessed here in Singapore for a large number of hotspots which translates to a very limited coverage area.
Especially in urban city environment consisting mainly of concrete jungles.

Ironically, Singapore & Malaysia's regulation for LoraWAN max EIRP limit is 27dbm (500mW); same as the hardcoded value prior to PoCv11 as opposed to the blanket 16dbm (40mW) defined for AS923 in PoCv11.

Is there any consideration of adopting country specific EIRP limit instead of 16dbm across the entire AS923 in the near future as initially suggested by @Trinitrophenol81 ?

**Comment by abhay** [comment] 2021-12-15 04:50
HIP 45 and LoRaWAN subregions are likely the only way we could support this on chain. The governance process to getting HIP 45 and the DeWi LoRaWAN committee are the right venue for enacting this change on the network. I'll close this issue for now since it is no longer part of the miner codebase.

**Closed by abhay** 2021-12-15 04:50 UTC
