### ISSUE TITLE
No Sent beacon and Reward HNT within 1 month (Everything went lose after the 2021.10.27.0 firmware update)

### ISSUE THREAD

**Issue by Mikael1993** [helium/miner#1245] opened 2021-11-22 11:50 UTC
I do not know what the problem really is
I'm sure everything is fine on my part
I have not sent any beacon for 1 month and all my witnesses have left me

What should I really do?

![Screenshot 2021-11-22 at 15-22-18 Helium Explorer](https://user-images.githubusercontent.com/94840296/142884348-0f401b4f-5f64-496a-9878-d04620ce3a54.png)
![Screenshot 2021-11-22 at 15-22-32 Helium Explorer](https://user-images.githubusercontent.com/94840296/142884354-ce8dd282-cd2c-41a6-8a2e-c66b9c7a0f63.png)
![Screenshot 2021-11-22 at 18-33-08 Helium Explorer](https://user-images.githubusercontent.com/94840296/142884576-a2ac746d-80a3-4570-a141-fc35db82ed5c.png)
![Screenshot 2021-11-22 at 18-33-28 Helium Explorer](https://user-images.githubusercontent.com/94840296/142884584-bbb2c110-f942-4ab0-8bde-8ebee0827e94.png)

**Comment by shawaj** [comment] 2021-11-22 14:42
You are in Iran? And you have EU868 right?

**Comment by Mikael1993** [comment] 2021-11-22 14:48
@shawaj
yes
EU868

**Comment by shawaj** [comment] 2021-11-22 14:52
You maybe need to reach out to Bobcat to see if they can see any logs on it.

Is it definitely synced and on the latest firmware?

**Comment by Mikael1993** [comment] 2021-11-22 14:57
Yes, everything went well for 3 months and it was great
Suddenly, after the 2021.10.27.0 update, this happened and we reached zero

**Comment by ElYoM** [comment] 2021-11-22 15:52
> You maybe need to reach out to Bobcat to see if they can see any logs on it.
> 
> Is it definitely synced and on the latest firmware?

It is a Helium problem, see here : https://github.com/helium/miner/issues/1205

**Comment by Mikael1993** [comment] 2021-11-22 15:53
[ Absolutely no mining activity since mandatory helium hotspot firmware 2021.10.27.0 (0 beacon/0 witness, only challenges)](https://github.com/helium/miner/issues/1205) #1205

**Comment by Mikael1993** [comment] 2021-11-22 15:56
@ElYoM 
I have been told for 14 days that we are investigating

**Comment by ElYoM** [comment] 2021-11-22 16:21
> @ElYoM I have been told for 14 days that we are investigating

Where did you get this answer?

**Comment by licentia88** [comment] 2021-11-22 16:27
helium owes a compensation reward to all these miners..

**Comment by Mikael1993** [comment] 2021-11-22 16:39
> 
![Screenshot 2021-11-22 at 20-07-56  BOBCAT  Re Decrease in income within 10 day - mikaeltrader1993 gmail com - Gmail](https://user-images.githubusercontent.com/94840296/142900295-bab2b762-f580-49fc-b79a-69a0d18a0259.png)

**Comment by Mikael1993** [comment] 2021-11-22 16:39
> > 
> 
> ![Screenshot 2021-11-22 at 20-07-56 BOBCAT Re Decrease in income within 10 day - mikaeltrader1993 gmail com - Gmail](https://user-images.githubusercontent.com/94840296/142900295-bab2b762-f580-49fc-b79a-69a0d18a0259.png)

**Comment by Mikael1993** [comment] 2021-11-22 16:40
> > @ElYoM I have been told for 14 days that we are investigating
> 
> Where did you get this answer?
![Screenshot 2021-11-22 at 20-07-56  BOBCAT  Re Decrease in income within 10 day - mikaeltrader1993 gmail com - Gmail](https://user-images.githubusercontent.com/94840296/142900433-b75df0c2-0b25-4448-bad6-3a9c2ebdc159.png)

**Comment by ElYoM** [comment] 2021-11-22 18:28
> > > @ElYoM I have been told for 14 days that we are investigating
> > 
> > 
> > Where did you get this answer?
> > ![Screenshot 2021-11-22 at 20-07-56  BOBCAT  Re Decrease in income within 10 day - mikaeltrader1993 gmail com - Gmail](https://user-images.githubusercontent.com/94840296/142900433-b75df0c2-0b25-4448-bad6-3a9c2ebdc159.png)

OK, thank you. However, the mining features are the responsibility of Helium and the miner's firmware. ;)

**Comment by Mikael1993** [comment] 2021-11-22 18:34
> 

I hope they see these problems and think about solving them

**Comment by Chinik12** [comment] 2021-11-23 14:43
I have SENSECAP and from 17days no election for send beacon, why? it's random, but in 17 days a lot of block and election.
[Activity](https://explorer.helium.com/hotspots/1121u7LTwLwLKDwCHzkVmj4uv8CxDxcPLwxUJzSsT1PkDk26Gjrv/activity)
![image](https://user-images.githubusercontent.com/93588105/143044676-65018a8d-a7c0-462e-97fe-93df09e437cc.png)
![image](https://user-images.githubusercontent.com/93588105/143044708-c8152bf2-77b0-418d-bc9e-3f7bab81a272.png)

**Comment by bertonhe** [comment] 2021-11-24 08:50
no reply from the helium team

**Comment by LinusFly74** [comment] 2021-11-24 09:57
> no reply from the helium team

It's incredible.....

**Comment by MolnarSzabi** [comment] 2021-11-24 11:55
Try to change your public ip. Just reset your router and also disable port forwarding for now then enable it back. For me changing my public ip fixed the problem. also check the discussion here: https://discord.com/channels/404106811252408320/908033438064467978

**Comment by techygeekshome** [comment] 2021-11-24 11:57
> Try to change your public ip. Just reset your router and also disable port forwarding for now then enable it back. For me changing my public ip fixed the problem. also check the discussion here: https://discord.com/channels/404106811252408320/908033438064467978

This worked for me from yesterday. Slowly getting back to normal now.

**Comment by Dniik** [comment] 2021-11-24 20:06
Same here. 
I have static IP and port 44158 is open.
My bobcat "Sent Beacon" **2. Novemver** and from this date only witnessed and challenged.
I have good spot and usualy get about 15 witnesses but now 0 **because last beacon was send 22 days ago** 
![obrazek](https://user-images.githubusercontent.com/94994704/143304616-8f49a7e7-0b1f-4125-830b-b6a5518db9ed.png)
![obrazek](https://user-images.githubusercontent.com/94994704/143305954-68ffc954-002f-4b49-a111-02eb65572eb9.png)

Activity drop and i dont know why. 
![obrazek](https://user-images.githubusercontent.com/94994704/143304899-2dcac802-6a80-40bb-a47a-b942b9154c24.png)

**Comment by LinusFly74** [comment] 2021-11-24 20:21
you ip is banned from your ISP?
try with smartphone (you can't change ip address)

Inviato da Yahoo Mail su Android 
 
  Il mer, 24 nov, 2021 alle 21:06, ***@***.***> ha scritto:   


Same here.
I have static IP and port 44158 is open.
My bobcat "Sent Beacon" 2. Novemver and from this date only witnessed and challenged.
I have good spot and usualy get about 15 witnesses but now 0 because last beacon was send 22 days ago



Activity drop and i dont know why.


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MolnarSzabi** [comment] 2021-11-24 20:32
Talk with your ISP/Provider to change your public ip. Make sure it changes and your problems should be resolved.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Dniik** [comment] 2021-11-24 21:04
I change ISP about 10 days ago. My IP is not banned.

**Comment by yogeshnichal** [comment] 2021-11-25 18:18
from last 8 days no sent beacon..
I have an outdoor antenna on rooftop, LMR400 cable, not relayed, in city, fast internet connection
I've multiple times checked my wires and antenna.
any one help... What should I do?
![Shot 0168](https://user-images.githubusercontent.com/56922233/143487209-31c9d081-622a-4ff8-8951-53ef5a4a8593.png)

**Comment by mbhmirc** [comment] 2021-11-26 17:46
@vihu Please combine into 1205

**Comment by Chris-S44** [comment] 2021-11-27 07:24
This is the update that killed one of mine on LTE. 
![Uploading Screenshot_20211127_092325.jpg…]()

**Comment by amirhaleem** [comment] 2021-11-29 21:07
probably a dupe of #1205, closing for now

**Closed by amirhaleem** 2021-11-29 21:07 UTC

**Comment by bkauii** [comment] 2021-12-07 23:58
I am still not sending or receiving beacons

https://explorer.helium.com/hotspots/112qPFRwNUEj86jhqLhaPCRTKNEZwsbr5ZUyLkRN5PKe49dyPnRt/activity
https://explorer.helium.com/hotspots/112MAoribtafFw3Z66Zv82wuajJTxQVjoeM7v9PRfTorsAepxN6c
