### ISSUE TITLE
Fix build status

### ISSUE THREAD

**Issue by CruiseMan** [helium/miner#502] opened 2020-09-03 04:02 UTC
Hard to tell if current code is ready for deployment when build fail.

**Comment by fvasquez** [comment] 2020-09-17 05:15
Are you a bot? Explain how the build failed for you.

**Comment by CruiseMan** [comment] 2020-09-20 19:18
> Are you a bot? Explain how the build failed for you.

Is this difficult to understand ?.
<img width="978" alt="Screen Shot 2020-09-20 at 12 17 18 PM" src="https://user-images.githubusercontent.com/15807643/93720047-6c7d1380-fb3b-11ea-883f-709becabdb30.png">

**Comment by CruiseMan** [comment] 2020-09-20 19:19
How can you merge anything on master if mater can't pass tests.

**Comment by CruiseMan** [comment] 2020-09-20 19:21
I wanted to buy helium, and went see github and found may repose have master in red status, which tell me code maintainers doing bad job. Not acceptable.

**Comment by fvasquez** [comment] 2020-09-21 13:00
As @CruiseMan points out the automated tests run against the source code in this repo are known to fail sporadically. Part of the problem is that the full test suite takes too long to run. While there is still a long way to go, Helium engineers are working towards improving the tests so that we can rely on them again.

**Comment by Vagabond** [comment] 2020-09-21 17:59
Yes, we are aware this is an issue. There are several causes here; the buildkite environment can be a bit more unreliable than a local machine, some tests are racy and some tests are "known broken" and we haven't had time to go back and fix them. We do use the tests internally to validate our releases, but there is some internal knowledge used to distinguish a bad failure from a good one.

I hope to dedicate some time to fixing this soon. That said, this issue is not a specifically actionable item as it's really a matter of test philosophy (we could make the tests green by simply commenting out all the unreliable tests but we'd prefer to actually work towards fixing them), so we will be closing this issue.

**Closed by Vagabond** 2020-09-21 17:59 UTC
