### ISSUE TITLE
Significant performance drop for hotspots connected with 4G/LTE

### ISSUE THREAD

**Issue by wolasss** [helium/miner#1208] opened 2021-11-15 16:09 UTC
After libp2p fix 2021.11.11.0 and fixing not_found in the peer book I noticed some of my miners are performing a bit better than others. It turns out that all of my miners connected with 4G/LTE internet are performing poorly and rarely beacon and witness others (sometimes 10 days without a beacon) while the others connected with fiber/cable internet connection perform way better (beacon more often - sometimes 1-3 times a day) and witness more hotspots. 

After bringing up this issue in the helium discord I have received many PMs from the people that noticed the exact same thing. 

Seems there is some kind of race condition/timeout issue that discriminate hotspots with slower internet connection causing them to underperform

**Comment by ProTechEx** [comment] 2021-11-17 06:31
Helium Team would reply you with:
Contact your Vendor for assistance... it is most probably hardware related. check your antenna cables. 

All the issues has nothing to do with Helium's Firmware

**Comment by Harv2021** [comment] 2021-11-17 22:25
> Helium Team would reply you with: Contact your Vendor for assistance... it is most probably hardware related. check your antenna cables.
> 
> All the issues has nothing to do with Helium's Firmware

And then the vendor will tell you to contact Helium to take a look....

**Comment by jakub2907** [comment] 2021-11-22 11:28
I have 11 miners. 9 are working on LTE and 5 of those are flatlined. They have been working fine before. About 3 weeks ago they went silent and are just challanging. Set ups are healthy with antennas outside. Ports opened. Discovery mode showed they have wintesses but they just will not beacong or wittness within the network. It's hard to understand as the reamining 4 that are also on LTE are working well. Beaconing and witnessing at a healthy rate.

**Comment by Mimik14** [comment] 2021-11-22 12:06
I have the same problem as you. Since the 4th of November there are big problems with hotspots connected via 4G. I have a total of 12 hotspots of which 8 are with LTE. 
I have heard many times that it is the provider, but this is not the case because I already have the same provider for 4 months and everything went well until the 4th of November.
Helium said on that there are problems with the peerbook and I think that has to do with the 4G network. Helium does not give any details about this....

**Comment by hcl-83** [comment] 2021-11-22 12:09
Hello,
I have 10 rak v2 hotspots.
Two are working on fiber connection and work well but rest on 4g/lte connection have flatline from 4th no beacon no witness.
Help Helium network what is going on

**Comment by jsloane** [comment] 2021-11-22 12:21
I also notice this problem. I have 3 SenseCAPs that have basically flatlined since around the 4th of November. All 3 are using 4G connections with Wireguard VPN for port forwarding.

**Comment by aemla** [comment] 2021-11-22 12:28
I have a bunch of hotspots that are on LTE connection. All of them have static IPs and are not relayed.
Three of my hotspots have almost 0 activity - they are only creating challenges, not beaconing and sometimes manage to get 1 witness per day. The first one does almost nothing since Nov 7-8, the second one since Nov 10-11 and the third one since Nov 17-18.
All of them had a lot of activity before that.

**Comment by wolasss** [comment] 2021-11-22 22:08
> Three of my SenseCAP hotspots have almost 0 activity - they are only creating challenges, not beaconing and sometimes manage to get 1 witness per day. Discovery mode shows a lot of responses. The first one does almost nothing since Nov 7-8, the second one since Nov 10-11 and the third one since Nov 17-18.

Yea I can really relate to that, but in my case, it concerns 1 Nebra, 2 Syncrob.it miners, and 1 Sensecap so it seems it is not a brand specific issue but rather a network issue. The difference in beaconing is really significant (see average 7d beacons): 

<img width="480" alt="Screenshot 2021-11-22 at 23 04 01" src="https://user-images.githubusercontent.com/1525324/142942292-262232ed-022d-4f15-893d-da7d9e7aaace.png">
<img width="482" alt="Screenshot 2021-11-22 at 23 04 12" src="https://user-images.githubusercontent.com/1525324/142942296-2e07fd47-39be-48dd-8d4b-d05565d19702.png">
<img width="480" alt="Screenshot 2021-11-22 at 23 05 02" src="https://user-images.githubusercontent.com/1525324/142942297-37cbdabb-3f3d-4822-8ec9-3b9c8d32d061.png">
<img width="480" alt="Screenshot 2021-11-22 at 23 04 28" src="https://user-images.githubusercontent.com/1525324/142942299-8b23f64a-5bda-4b6a-90d9-f9fe90c95dae.png">

**Comment by vjjramos** [comment] 2021-11-23 16:07
Mine as well. I'm on LTE and it hasn't sent any beacons from the past 19 days and also have 0 witnesses.

**Comment by Thomas-LEB** [comment] 2021-11-23 16:44
Same issue

**Comment by hcl-83** [comment] 2021-11-23 16:50
Last 24h same set LTE center of city with many hotspots

![IMG_20211123_174656](https://user-images.githubusercontent.com/94841362/143067828-4e831f28-27ce-4b6e-9975-948953a795fd.jpg)
![IMG_20211123_174804](https://user-images.githubusercontent.com/94841362/143067831-0a9116f9-384e-47fe-b662-1d8c42df2a1b.jpg)

**Comment by Chris-S44** [comment] 2021-11-23 20:43
I am having the same problem. I have 4 sensecap miners. 2 on fibre and 1 on adsl are working great. I have one on LTE that stopped working on 2021.11.12 all it started doing was challenging beaconers over and over.
I switched it over to a faster lte connection with a static public ip but nothing changed.
After the first big block blockchain issue it witnessed 3 beacons then went dead again.
I then put in a new SD card. After the second blockchain outage it sent one beacon and had one witness and went dead again.
I have checked over everything. Miner is not relayed, Nat is none and it is always fully synced. Just not performing and poc.
Why is this mostly happening on lte now?
A month ago this same miner on the same lte was my best beaconing miner.

**Comment by radicale** [comment] 2021-11-24 11:51
I have the same prob on 3 sensecap units connected through LTE, but two with full VPN / static IP.  Also had 1 bobcat with the same on DSL.   I don't think the issue is specific to LTE.  It seems like the p2p network is fragmented, and if you are on the wrong side, you get flatlined.

**Comment by SteveisIT** [comment] 2021-11-24 12:32
It's p2p issues as usual. They cannot pinpoint the problem as they have applied too many temporary band-aids in the past, and then plastered over those. This is the state of the network until end of q1 2022.

**Comment by Dniik** [comment] 2021-11-24 22:29
Same problem. 
Connected with 4G/LTE and 70% - 80% drop.
Last sent beacon is 2. November

**Comment by bilalhp** [comment] 2021-11-24 23:44
I confirm that changing IP or closing the port 44158 to let the miner relayed is helping to get witnessing activity back, but the outcome is not 100% success of all beacons being witnessed is rewarded.

**Comment by cany25** [comment] 2021-11-25 13:38
I think i have the same problem. One of my bobcats is on LTE and is placed (for almost 4 months now) about 30 m high in an area with hundreds of reachable hotspots around it. 
For 3 months it had ~100 witnesses and witnessed beacons about 30-40 times per day. For 3 weeks now it's almost flat lining, witnessing at best 3 times per day with rewards ~0.003 HNT, it didn't send a beacon for 18 days now.
Does anyone have a clue what the problem could be? Setup is unchanged since installation.

Last Beacon
![grafik](https://user-images.githubusercontent.com/87498131/143448982-1246a71e-3329-4fc7-b647-a168e4a04880.png)

![grafik](https://user-images.githubusercontent.com/87498131/143450684-78835037-a0c7-4ba5-8e50-e2e76de1e928.png)

Other 2 bobcats are on fiber and are working almost like before

**Comment by hcl-83** [comment] 2021-11-27 07:43
Maybe it's good to send mail to support@helium.come with this thread. i send one right now do the same.

**Comment by Thomas-LEB** [comment] 2021-11-28 00:28
So my miner (LTE with VPN) which was flatlined since the 4 of November update started to witness again, after I removed the VPN. 
Now the miner is relayed, but at least I'm witnessing more frequently.
The VPN IP address that I was using is in another country, so I think that the helium team introduced a IP geolocation blocker, and this is why I was not getting any activity.
I will keep on checking and see if this is a solution 
I will keep you guys updated

**Comment by Pappa-Bear** [comment] 2021-11-28 04:59
Same for me. After reading that it might be an LTE issue, I went through to one of my hosted sites, turned the LTE off and moved the miner (a SenseCap) from onto the hosts fibre wifi. Almost instant change in terms of witnessing:
![image](https://user-images.githubusercontent.com/95157626/143730180-d63b92dd-ea7d-4c67-bc01-b1179eb4bbf5.png)

Still waiting for it to beacon, but I've gone from 2 weeks of flatline other than a tiny challenge every 6 hours or so, to way activity like it should be and all I've changed in the setup is moving off of LTE.

Before turning off the LTE, I also did a speedtest and the LTE connection was really good

**Comment by cany25** [comment] 2021-11-28 12:07
> I confirm that changing IP or closing the port 44158 to let the miner relayed is helping to get witnessing activity back, but the outcome is not 100% success of all beacons being witnessed is rewarded.

Thanks for that. Changed IP and closed port 44158 for 6 h 2 days ago, it kinda helps, witnessing 6-7 times per day now.  
21 days without a beacon, that really grinds my gears :(

**Comment by Dniik** [comment] 2021-11-29 11:03
Using LTE and after 

> Same problem. Connected with 4G/LTE and 70% - 80% drop. Last sent beacon is 2. November

After using VPN everything back to normal.

**Comment by wolasss** [comment] 2021-11-29 11:08
I can also confirm that changing your IP from static to dynamic, or redirecting the traffic through VPN partially fixes the activity issue.

**Comment by Chris-S44** [comment] 2021-11-29 11:24
> > Same problem. Connected with 4G/LTE and 70% - 80% drop. Last sent beacon is 2. November
> 
> After using VPN everything back to normal.

What is the easiest way to setup a vpn?

**Comment by Dniik** [comment] 2021-11-29 11:45
> > > Same problem. Connected with 4G/LTE and 70% - 80% drop. Last sent beacon is 2. November
> > 
> > 
> > After using VPN everything back to normal.
> 
> What is the easiest way to setup a vpn?

My router support OpenVPN. 
So I buy VPN on privateVPN and configure my router. I am using teltonika router.

**Comment by fenschi1981** [comment] 2021-11-29 11:56
same here....
Congstar LTE with IPv4, port open, fritzbox 6820, listenip, ping, peerbook, all fine ---> only challenged beaconer, no sent beacons, no witnessed beacons...
about 3 hrs ago, i changed to DSL --> 1 sent beacon, 6 witnessed beacons

but i seems to be random: another hotspot o2 LTE (only ipv6), fritzbox 6820 works 

crazy

**Comment by Tobay-cmd** [comment] 2021-11-29 12:12
> same here.... Congstar LTE with IPv4, port open, fritzbox 6820, listenip, ping, peerbook, all fine ---> only challenged beaconer, no sent beacons, no witnessed beacons... about 3 hrs ago, i changed to DSL --> 1 sent beacon, 6 witnessed beacons
> 
> but i seems to be random: another hotspot o2 LTE (only ipv6), fritzbox 6820 works
> 
> crazy

I have the 100% exact same setup on all my miners. Actually I believe it is even more complex with German Telekom than the general LTE issue with Helium...

What I can say is the following:
1. I (was) am using internet.t-d1.de APN to get a clean IPv4.
2. On 5 setups this lead to flatlines and the "challange beaconer, no sent beacons" problem. On 1 setup everything was perfectly fine.
3. It seems like the alternative APN does not work on all LTE antennas properly anymore since the only one working setup was having 15-25ms latency, all others 30ms+
4. "Fixed" the 5 other setups by closing the ports and removing the alternative APN (by the way this leads to much better up-/download speed)
5. Then my last setup got the same issue all of a sudden and I could resolve it by activating the Ipv6 function on Fritzbox with 3gpp v8 (even I read from others that this does not work for the alternative APN and I do not receive a Ipv6 (in my eyes))
6. The general problem with Telekom on resolving American servers, is part of the problem aswell. But I have no proof.
7. I will try to VPN to my VDSL VPN and see if it helps

Maybe someone else can help, last thing I did was changing DNS to 1.1.1.1 & 8.8.8.8, but actually I guess this is just cosmetics and did not change anything

**Comment by fenschi1981** [comment] 2021-11-29 12:20
> I have the 100% exact same setup on all my miners. Actually I believe it is even more complex with German Telekom than the general LTE issue with Helium...

You're on helium-discord? could you sent me an PN there, pls?

**Comment by amirhaleem** [comment] 2021-11-29 21:08
probably a dupe of #1205, closing for now

**Closed by amirhaleem** 2021-11-29 21:08 UTC

**Comment by Mikael1993** [comment] 2021-12-03 06:14
Let's announce here that maybe the Helium team saw this again...
[Did the 2021.11.30.1 update solve the problem of not sending beacon and not having a witness for you? ](https://github.com/helium/miner/issues/1273)
#1273
