### ISSUE TITLE
Miner is not syncing after unplugging it for 2 hours

### ISSUE THREAD

**Issue by naitsimp** [helium/miner#1095] opened 2021-09-26 18:01 UTC
I unplugged my Sensecap Miner for around 2 hours.
Since than the Miner is not syncing new Blocks. 
It is stuck on Block 1027315 (no Challenges, No Beacons, no Witnessing, only Packet Transfer is working). 
CPU usage dropped from around 25% to around 8%.

**Comment by janzone** [comment] 2021-10-04 13:57
Is it fixed and how did you do it?

**Comment by bitlite** [comment] 2021-11-09 06:40
Log into your Miner Web Page, Click on RESET MINER, this will clear the firmware and blockchain and start downloading the firmware and build the blockchain again. After 30 minutes, log back in and click FAST SYNC and wait about 20 minutes. It should be resolved. If so, please close this ticket.

If issue is still there, you MUST contact your Miner Vendor and open up port 22 for them to remote into miner to fix it, if they offer this service (Bobcat support does this).

Either way, this happens on multiple vendor equipment as well. I can confirm this happened on a Bobcat.

**Comment by abhay** [comment] 2021-12-15 04:53
This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.

**Closed by abhay** 2021-12-15 04:53 UTC
