### ISSUE TITLE
Hotspot online, sending beacons but not receiving witnesses.

### ISSUE THREAD

**Issue by J-Frodo** [helium/miner#1452] opened 2022-02-25 23:45 UTC
As the title says. Hotspot name is 'Gorgeous Wool Shell'.
Explorer link: https://explorer.helium.com/hotspots/111Qg7uccakNK7EZUP4G86F45chq2YMKD8F3fufxzVizqYwdQpm

**Comment by MarcDietschi** [comment] 2022-02-27 08:14
Same issue (and some others like Bluetooth connection interruptions) with my Nebra Rock Pi 4 Indoor Miner: Firmware Version | 2022.02.22.0 (8465d62)

**Comment by RepRapid** [comment] 2022-03-10 23:16
I can say that since the most recent update, This has affected several hotspots, I have noticed that my hotspot is having this occurrence as well, I have checked in the explorer map, by clicking on the receipt and copy paste the challenger into the search bar, To check if they are relayed, some have been. Some have not been. I have gone further to see if those hotspots that have challenged me, have had this issue with other hotspots they have challenged, I noticed sometimes, it is the case. Sometimes it is not, and does not seem to be correlated between Relayed or with others. The first time I searched the Challenger even happened to be on the deny list which made some sense, but not in other occasions.

**Comment by aledantas2k12** [comment] 2022-03-16 05:30
Latest update broke it. I was doing well before...

**Comment by KhalidKhazal** [comment] 2022-03-18 21:55
I have the same issue, I used to have witness activities every half an hour or less, now I rarely see witnessing activities and my miner remains with zero activities for more than 8 hours sometime, I tried to reach out to miner manufacturer support and they confirmed that all my hardware is working perfectly fine after diagnosing back and forth!! It looks like a blockchain issue and I'm not sure how to get it fixed :(

**Comment by meowshka** [comment] 2022-05-17 23:49
@J-Frodo please contact manufacturer of your hotspot directly and make sure have the latest firmware version. Here's their discord: https://discord.com/invite/2Barf528uj

**Closed by meowshka** 2022-05-17 23:49 UTC
