### ISSUE TITLE
Hotspots stuck on blockchain before and after last update (No activity for +24 hours)

### ISSUE THREAD

**Issue by RKappaN** [helium/miner#1024] opened 2021-09-02 18:51 UTC
**I have 10 hotspots (Rak V2) and 7 are being affected by this problem:**

Two of my hotspots suddenly stopped the activity & sync at 1 Sep 2021, 6:14am and 6:19am (5 minutes difference). **Helium hiker can reach the hotspots** and they have inbound and outbound green connection - so, no problems with the internet connection. I tried to power cycle them, but didn't work at this time.

The hotspots are stuck somewhere in blockchain and can't do any activity because of that. I reported this issue at Discord and talked with other people that are facing the same issue. Some hours after, Helium team posted a **new announcement:**

_"**hashc0de** — Yesterday at 6:22 PM
@here Blockchain Release: Stability and Performance Updates..."_

After that announcement more 5 of my hotspots suddenly stopped doing activity too. Now, **it's been 24 hours without any activity** or change in sync. I'm checking the Helium API and I see that the block height does't change at all - it's stuck.

At discord, several people are reporting this. Most of them that are reporting this issue have Rak V2.

_Obs: All of my hotspots are installed at rooftops via PoE and were working fine for months. I'm writing this because they usually have a good performance, so it's not normal to don't have any activity for more than an hour._

**A guy that I spoke via Discord told me that cloning the SD from a working hotspot to an hotspot that isn't working can fix this:**

"I am sure the problem is somehow firmware related because I cloned the micro SD from a working hotspot and pasted it in two hotspots that weren't doing activity. I changed the first one this morning and the second a couple of hours ago:

The one changed this morning already earned around 1HNT in less than 12 hours so it's fully working; The other one seems starting to working again now.

All the hotspot still result online and after I tried to ping them with helium hiker I got a round-trip time so the hotspot was online but still unable to work.

Btw the "not very fast but still working" solution as I stated is to change the micro SD from a working hotspot so if helium can't fix it you can go and fix it by yourself, it's painful but it works".

Even at Facebook, people are reporting this issue. You can search this issue at discord by searching for this terms: "no activity", "stuck", etc...

I don't have more details to add. Thank you

![hotspots](https://user-images.githubusercontent.com/90000302/131899782-45142b10-06e3-4d12-b9cd-80105bb66313.jpg)

**Comment by Sneak85** [comment] 2021-09-03 03:57
Would like to add to this issue. I have several Hotspots, OGs, Rak V1.5 and RakV2. OG's and Rak V1.5 are fine. Currently 7/10 of my Rak V2 are syncing and making extremely slow progress if any. Of the remaining 3, 2 of them are not yet asserted, so that leaves 1 functioning RakV2 running.

**Comment by firedawg225** [comment] 2021-09-03 04:42
I have a RakV2. Hot spot Long Orchid Kangaroo. It it at 990320. Earlier today i was at 987,387. I'm still 4.2k behind and was 6.7 before. Been down for 24 hours +.  At the current rate i won't catch up on the block for at least 2 or 3 mores days. if that. This was my Central hotspot and have lost all rewards, witnesses, and so on. Currently running 3 hotspots in 3 hexes. Only one affected but other around have sync issues too.

**Comment by crpto-afk** [comment] 2021-09-03 04:48
Same issue. It’s been three days now and it’s stuck on 99.54% sync and won’t mine. It’s very frustrating.

**Comment by crpto-afk** [comment] 2021-09-03 04:48
Also a RAKv2 miner

**Comment by blum81** [comment] 2021-09-03 04:49
RakV2 here as well.  Rough Fuzzy Weasel, also stuck on syncing at block 988922.  Been down syncing since the 2021.08.31.1 update was announced.  

It's really disappointing that Helium is basically just telling us to wait and deal with it.  At this rate being 5.5k blocks out of sync, it'll be another 3-4 days without my miner being online.

**Comment by BitDegent30** [comment] 2021-09-03 04:55
Bobcat 300.  Melodic Taupe Beetle is stuck syncing. Please help resolve the issue. A lot of rewards are being missed. Thank you.

**Comment by dpetrov** [comment] 2021-09-03 05:08
Same issue here as well. 4 RAK v2 are stuck o. Syncing for 3 days already.

**Comment by Sani1991** [comment] 2021-09-03 06:21
Same here for my RAKv2 young-frost-hyena.
It starter syncing yesterday when the new firmware update was released and is at 99.3% atm. From 99 to 99.3 it took 24hours

**Comment by PidgeyBE** [comment] 2021-09-03 06:28
I'm experiencing the same with a Sensecap hotspot. It's been running for weeks until the 8.31 firmware announcement was made. It seems to me the issue is in the blockchain variables update, because my hotspot stopped syncing 15h before sensecap released the firmware upgrade...

**Comment by blum81** [comment] 2021-09-03 06:35
> I'm experiencing the same with a Sensecap hotspot. It's been running for weeks until the 8.31 firmware announcement was made. It seems to me the issue is in the blockchain variables update, because my hotspot stopped syncing 15h before sensecap released the firmware upgrade...

if you stopped syncing before sensecap released the firmware then your issue might not be related because you would have still been on 24.4.  

My 5 sensecap were all synced before sensecap announced, then they all did the upgrade around the same time, and came back up with the new version and continued on the blocks they were on.  I watched the process through the sensecap dashboard.

**Comment by arcthelac** [comment] 2021-09-03 06:36
Its been 36hrs and my hotspot is still syncing, latest update 08.31.01 really stopped the activities on my hotspot. Mine is Rak V2, was running fine for 2 months until last 2 days.

**Comment by PidgeyBE** [comment] 2021-09-03 06:41
> > I'm experiencing the same with a Sensecap hotspot. It's been running for weeks until the 8.31 firmware announcement was made. It seems to me the issue is in the blockchain variables update, because my hotspot stopped syncing 15h before sensecap released the firmware upgrade...
> 
> if you stopped syncing before sensecap released the firmware then your issue might not be related because you would have still been on 24.4.
> 

I'm not sure... This issue is about hotspots that got stuck both right before and after the update, right?

**Comment by abhay** [comment] 2021-09-03 06:45
Closing as duplicate of #1023.

**Comment by blum81** [comment] 2021-09-03 06:45
> > > I'm experiencing the same with a Sensecap hotspot. It's been running for weeks until the 8.31 firmware announcement was made. It seems to me the issue is in the blockchain variables update, because my hotspot stopped syncing 15h before sensecap released the firmware upgrade...
> > 
> > 
> > if you stopped syncing before sensecap released the firmware then your issue might not be related because you would have still been on 24.4.
> 
> I'm not sure... This issue is about hotspots that got stuck both right before and after the update, right?

This is more for after the hotspots were updated to 31.1. then went down.

**Closed by abhay** 2021-09-03 06:45 UTC

**Comment by PidgeyBE** [comment] 2021-09-03 06:51
> > > > I'm experiencing the same with a Sensecap hotspot. It's been running for weeks until the 8.31 firmware announcement was made. It seems to me the issue is in the blockchain variables update, because my hotspot stopped syncing 15h before sensecap released the firmware upgrade...
> > > 
> > > 
> > > if you stopped syncing before sensecap released the firmware then your issue might not be related because you would have still been on 24.4.
> > 
> > 
> > I'm not sure... This issue is about hotspots that got stuck both right before and after the update, right?
> 
> This is more for after the hotspots were updated to 31.1. then went down.

Okay.. Anyway, Sensecap support replied this to me:
```
Hi@pidgey , I find you device is repairing itself by re-downloading the ledger of each block. And it is repairing the 989246 block now.  2021-09-03 01:55:33.916 159 [info] <0.1581.0>@miner:handle_info:461 non-consensus block 989246 So I think your device will be fine soon. Please don't power it off after it finished syncing.
```
