### ISSUE TITLE
No activity in past 9 days

### ISSUE THREAD

**Issue by C4ngr3j0** [helium/miner#1249] opened 2021-11-22 20:31 UTC
My hotspot hasn't registered any activity in the past 9 days. It hasn't experienced witness, which isn't strange. What is strange is that it hasn't emited beacons nor challenges.

![image](https://user-images.githubusercontent.com/90414120/142930869-b01ca7bd-f584-442a-959e-9f19265b0375.png)

This is a common problem yet I have not seen a definite solution. Please help me out. Only 1 beacon (nothing)

Lastly: ffs, Helium was supposed to be a passive income!

**Comment by LinusFly74** [comment] 2021-11-22 20:50
help me please. bobcat zero Activity.  44158 ok, nat none, synced, last firmware, connection ok.   🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️😩😩

**Comment by MrCorv0** [comment] 2021-11-22 21:28
mine is the same... good luck getting an answer.. Helium and bobcat never respond

**Comment by C4ngr3j0** [comment] 2021-11-22 21:54
Mine is a Heltec

**Comment by MolnarSzabi** [comment] 2021-11-22 21:58
My bobcat doesn't send beacons or get witnesses anymore even tho it used to work fine untill the mandatory update, but since saturday it isn't working. Activity is close to none because only challanges are being created. It is in a good location, no relay, good internet speed and everything checked really. Accurate location and antena so I can't imagine what happened. The hotspot's name is Breezy Clear Donkey.

**Comment by jaw2ay** [comment] 2021-11-23 02:37
having the same issue with nebra

**Comment by efe92** [comment] 2021-11-23 08:49
16 days same

**Comment by C4ngr3j0** [comment] 2021-11-23 14:58
ffs can someone of Helium say something?

**Comment by Chinik12** [comment] 2021-11-23 15:01
+1
i'm SENSECAP and from 17days no election for send beacon, why? it's random, but in 17 days a lot of block and election.
[Activity](https://explorer.helium.com/hotspots/1121u7LTwLwLKDwCHzkVmj4uv8CxDxcPLwxUJzSsT1PkDk26Gjrv/activity)
![image](https://user-images.githubusercontent.com/93588105/143044676-65018a8d-a7c0-462e-97fe-93df09e437cc.png)
![image](https://user-images.githubusercontent.com/93588105/143044708-c8152bf2-77b0-418d-bc9e-3f7bab81a272.png)

**Comment by LinusFly74** [comment] 2021-11-23 15:32
the project is rewarding those who live in medium-sized cities.  taking away earnings from those who have very few hotspots

Inviato da Yahoo Mail su Android 
 
  Il mar, 23 nov, 2021 alle 15:58, ***@***.***> ha scritto:   


ffs can someone of Helium say something?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by C4ngr3j0** [comment] 2021-11-25 01:24
Anyone resolved it? @jaw2ay @efe92 @MolnarSzabi @Chinik12

**Comment by efe92** [comment] 2021-11-25 01:55
i fix my problem. finally i wait 20 days and i got sent beacon and take 18 witness. i have no idea how this happened but i'm glad. i wish you solve your witness problem as soon as possible. @C4ngr3j0

**Comment by jaw2ay** [comment] 2021-11-25 03:11
Thought I resolved it took my nebra off vpn I guess they updated firmware
today, worked great for a few hours then stopped sending and receiving,  my
sensecap is now on the vpn and working fine.

**Comment by C4ngr3j0** [comment] 2021-11-25 05:09
@efe92 what did you do to fix it ? D:

**Comment by efe92** [comment] 2021-11-25 08:07
I just pray :D

**Comment by oplantis22** [comment] 2021-11-28 07:51
I have had the same problem with Bobcat Miner, last 10 days it does not complete synchronization, the gap is almost around 5000. 
I tried faster sync, reboot, resynchronization lots of time. It did not change. What can Ido I dont know.

**Comment by Thumbsup1** [comment] 2021-11-28 08:51
More than 20 days now not sending beacons. Only creating challenges and 1 or 2 witness a day if i am very lucky. I tried everything but still the same

**Comment by amirhaleem** [comment] 2021-11-29 21:07
probably a dupe of #1205, closing for now

**Closed by amirhaleem** 2021-11-29 21:07 UTC

**Comment by C4ngr3j0** [comment] 2021-11-30 21:59
@amirhaleem  wtf, it may be a dupe, but you closed that post as well. what the fuck

**Comment by Mikael1993** [comment] 2021-12-03 06:12
Let's announce here that maybe the Helium team saw this again...
https://github.com/helium/miner/issues/1273
#1273
